### PR TITLE
added text typing effect and other changes

### PR DESCRIPTION
**Pull request by Arjundotadex**

### CODE REVIEW

**Comment by Zoronium** [comment]
Hey @Arjundotadex 
can you please
- [ ] add a screenshot or video of the working for the same

Thx

**Comment by Arjundotadex** [comment]
yeah sure

**Comment by Arjundotadex** [comment]
https://user-images.githubusercontent.com/103199408/214845416-7a216393-1bd3-43d1-b792-928fd9df3a48.mp4

**Review by Zoronium — APPROVED** [review]
✅LGTM !!!

**Pull request merged**
